server:
  port: 8082
# 网关处理的服务类型的名称由下面的内容确定，同时限制了
# 文件的大小为5MB
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
# 配置服务的注册中心为我们搭建的Eureka注册服务中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

# 每间隔5秒发一次心跳, 10秒过期，认为死掉


# Eureka Client